name: Martin Porcheron
author: Martin Porcheron
title: Martin Porcheron
email: website@martin.porcheron.uk
lang: en-GB
description: >-
  Martin Porcheron is a Senior User Experience Researcher at Bold Insight, focusing on both qualitative studies of consumer technology and human factors studies of medical devices.

baseurl: ""
url: "http://localhost:4000"
permalink: /blog/:year/:month/:day/:title/
repository: mporcheron/porcheron.uk.git

# Social settings
social:
    browser:
        theme_colour: 3A3C45
    twitter:
        username: MPorcheron
        card: /assets/img/twittercard.png
        card_alt: A photo of Martin Porcheron
    github:
        username: MPorcheron
    scholar:
        user_id: xqQs-LEAAAAJ

github:
  repo: https://github.com/mporcheron/porcheron.uk/
  link_title: "View edit on GitHub"

# Build settings
plugins_dir: ./_plugins
plugins:
  - jekyll-menus
  - jekyll-optional-front-matter
  - jekyll-redirect-from
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-scholar
  - jekyll-target-blank
  - jekyll-titles-from-headings

# Generation
liquid:
  error_mode: strict
  strict_variables: false
  strict_filters: true

sass:
    style: compressed

jekyll-last-commit:
  date_format: '%d-%b-%Y %R'       # default: `%B %d, %Y`
  should_fall_back_to_mtime: false # default: `true`
  data_files_key: 'meta'           # default: meta

titles_from_headings:
    enabled: true
    strip_title: true
    collections: true

scholar:
  style: _bibliography/acm.csl
  locale: en
  source: ./_bibliography
  bibliography: "*.bib"
  bibliography_template: pub_reference
  details_layout: pub_bibtex.html
  details_permalink: /pubs/bibtex/:key:extension
  details_link: false
  sort_by: year, title
  order: descending, ascending

jekyll-minifier:
  compress_javascript: false
  compress_css: true
  exclude: 
    - 'feed.xml'
    - 'sitemap.xml'

defaults:
  - scope:
      path:            ""
    values:
      layout:          "page"
  - scope:
      path:            ""
      type:            "posts" 
    values:
      layout:          "post"
  - scope:
      path:            "assets/**/*.pdf"
    values:
      sitemap:         false

excerpt_separator: <!--more-->

exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
