name: Martin Porcheron
author: Martin Porcheron
title: Martin Porcheron
email: website@porcheron.uk
lang: en-GB
description: >-
  Martin Porcheron is a Senior User Experience Researcher at Bold Insight, focusing on both qualitative studies of consumer technology and human factors studies of medical devices.

baseurl: ""
url: "http://localhost:4000"
permalink: /blog/:year/:month/:day/:title/
repository: mporcheron/porcheron.uk.git

# Social settings
social:
    browser:
        theme_colour: 3A3C45
    twitter:
        username: MPorcheron
        card: /assets/img/twittercard.png
        card_alt: A photo of Martin Porcheron
    github:
        username: MPorcheron
    scholar:
        user_id: xqQs-LEAAAAJ

# Build settings
plugins_dir: ./_plugins
plugins:
  - jekyll-menus
  - jekyll-optional-front-matter
  - jekyll-redirect-from
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-scholar
  - jekyll-target-blank
  - jekyll-titles-from-headings

# Liquid config
liquid:
  error_mode: strict
  strict_variables: false
  strict_filters: true

# SASS generation
sass:
    style: compressed

# Title generation from headings
titles_from_headings:
    enabled: true
    strip_title: true
    collections: true

# Publications
scholar:
  style: _bibliography/acm.csl
  locale: en
  source: ./_bibliography
  bibliography: "*.bib"
  bibliography_template: pub_reference
  details_layout: pub_bibtex.html
  details_permalink: /pubs/bibtex/:key:extension
  details_link: false
  sort_by: year, title
  order: descending, ascending

# Exclude from minificartion
jekyll-minifier:
  compress_javascript: false
  compress_css: true
  exclude: 
    - 'feed.xml'
    - 'sitemap.xml'
#   uglifier_args:
#     harmony: true

# Sitemap configutation
defaults:
  - scope:
      path:            ""
    values:
      layout:          "page"
  - scope:
      path:            ""
      type:            "posts" 
    values:
      layout:          "post"
  - scope:
      path:            "assets/**/*.pdf"
    values:
      sitemap:         false

# Excerpt separator
excerpt_separator: <!--more-->

# Exclude from processing
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
