# Site information
name: Dr Martin Porcheron
author: Martin Porcheron
lang: en-GB
description: >
  Martin Porcheron is a Senior User Experience Researcher at Bold Insight, focusing on both qualitative studies of consumer technology and human factors studies of medical devices.
timezone: Europe/London

baseurl: ""
url: "http://localhost:4000"
permalink: /blog/:year/:month/:day/:title/
repository: mporcheron/porcheron.uk.git


# Contact links
contact:
  email: website@martin.porcheron.uk
  linkedin: https://www.linkedin.com/in/mporcheron/


# Social links
social:
  browser:
    theme_colour: E7EFEF 
  github:
    username: MPorcheron
    repo: https://github.com/mporcheron/porcheron.uk/
    link_title: "View edit on GitHub"
  scholar:
    user_id: xqQs-LEAAAAJ


# Build settings
plugins_dir: ./_plugins
plugins:
  - jekyll-email-protect
  - jekyll-last-commit
  - jekyll-menus
  - jekyll-optional-front-matter
  - jekyll-redirect-from
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-scholar
  - jekyll-target-blank


# Site building
defaults:
  - scope:
      path:            ""
    values:
      layout:          "page"
  - scope:
      path:            "assets/**/*.pdf"
    values:
      sitemap:         false

jekyll-last-commit:
  date_format: '%d-%b-%Y %R'
  should_fall_back_to_mtime: false
  data_files_key: 'meta'
  index_data_files: true
  index_static_files: true

titles_from_headings:
    enabled: true
    strip_title: true
    collections: true

scholar:
  style: bibliography/acm.csl
  locale: en
  source: ./bibliography
  bibliography: "*.bib"
  bibliography_template: pub_reference
  details_layout: pub_bibtex.html
  details_permalink: /pubs/bibtex/:key:extension
  details_link: false
  sort_by: year, title
  order: descending, ascending

liquid:
  error_mode: strict
  strict_variables: false
  strict_filters: true

sass:
  style: compressed

jekyll-minifier:
  compress_javascript: false
  compress_css: true
  exclude: 
    - 'feed.xml'
    - 'sitemap.xml'

excerpt_separator: >
  <!--more-->

exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
